### ISSUE TITLE
North Saami spellchecking is slow

### ISSUE THREAD

**Issue by albbas** [voikko/libreoffice-voikko#10] opened 2017-10-16 13:54 UTC
In LibreOffice on KDE Neon (Ubuntu Xenial/16.04 with updated KDE) the North Saami voikko-based spellchecker makes Writer quite slow. I haven't tested any other systems.

/usr/lib/libreoffice/program/soffice.bin --writer runs at 100% CPU utilisation.

I use the apertium-nightly packages for xenial.

An example document that triggers this behavior is found here: https://gtsvn.uit.no/freecorpus/orig/sme/admin/depts/other_files/samedikki_doaibma_2015.docx

Installed packages:
```
libreoffice-writer 1:5.1.6~rc2-0ubuntu1~xenial2
libreoffice-voikko 5.0-2
libvoikko1:amd64 4.1.1~r5827-0ubuntu1~xenial1
hfst-ospell 0.5.0~r352-0ubuntu1~xenial1
giella-sme 0.0.20150917~r158527-1~sid1
```

**Comment by hatapitk** [comment] 2017-10-25 19:04
Where does ```hfst-ospell 0.5.0~r352-0ubuntu1~xenial1``` come from? Ubuntu and Debian do not have anything newer than 0.4.5. Using version 0.4.5~r343-2.1 this bug cannot be reproduced because zhfst spellers do not appear to work at all.

**Comment by albbas** [comment] 2017-10-25 22:11
They come from the [apertium nightly/unstable repository](http://wiki.apertium.org/wiki/Install_Apertium_core_using_packaging), but right now libvoikko1 is broken due to api changes in hfst-ospell. Tino Didriksen said he would look into that breakage.

**Comment by hatapitk** [comment] 2018-08-15 19:50
I'm closing this as not reproducible but it is of course OK to reopen it if the issue can be reproduced. Most likely the observed slowness was related to some specific combination of dependent libraries or spellers.

**Closed by hatapitk** 2018-08-15 19:50 UTC
Labels: bug
